default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: development-testguru

test:
  <<: *default
  database: testdb-testguru

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
